<?php

/**
 * @file
 *
 * Installs the required object for Digitalus solution pack
 */

/**
 * Implements hook_install().
 *
 * @see islandora_islandora_required_objects()
 */
function islandora_digitalus_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_digitalus');
}

/**
 * Implementation of hook_uninstall.
 */
function islandora_digitalus_uninstall() {

}
