<?php

/**
 * @file
 * XML to HTML converter.
 *
 */


/**
 * Implements hook_menu().
 * Drupal menus allow urls to be used as function calls, giving Drupal gets much
 * of its power and flexibillty.
 * See https://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_menu/7
 */
function islandora_digitalus_menu() {
  return array(
    'admin/islandora/digitalus' => array(
      'title' => 'Digital Page Test Module',
      'description' => 'Configure the Digital Page solution pack.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_digitalus_admin'),
      'file' => 'includes/islandora_digitalus.admin.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}
/**
 * Implements hook_theme().
 *
 * We supply a pattern so we can overide templates at the theme level if needed.
 * we can append a pid to a template and the new template file will be called
 * (the pids colon should be replaced with a dash)
 */
function islandora_digitalus_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_digitalus' => array(
      'template' => 'theme/islandora-digitalus',
      'pattern' => 'islandora_digitalus__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_preprocess_theme().
 * This is a Drupal hook, not supplied by islandora.
 * Variables required for display are assembled here and passed to the template file
 * defined in the theme function.  The function defines islandora-digitalus, which
 * expands to islandora-digitalus.tpl.php.
 * The isandora object has been added to the $variables array by 
 * hook_CMODEL_PID_islandora_view_object(), whihc in this case is
 * islandora_digitalus_islandora_digitalusCModel_islandora_view_object
 * 
 */
function islandora_digitalus_preprocess_islandora_digitalus(array &$variables) {

  $islandora_object = $variables['islandora_object'];
  // Thumbnail.
  if (isset($islandora_object['TN'])) {
    $thumbnail_size_url = url("islandora/object/{$islandora_object->id}/datastream/TN/view");
    $params = array(
      'title' => $islandora_object->label,
      'path' => $thumbnail_size_url,
    );
    $variables['islandora_thumbnail_img'] = theme('image', $params);
  };
  
  //SEMANDRA - adding page image to $variables to display on page
/*  if (isset($islandora_object['image1'])) {
  	$page_image_url = url("islandora/object/{$islandora_object->id}/datastream/image1");
    $params = array(
      'title' => $islandora_object->label,
      'path' => $page_image_url,
    );
    $variables['islandora_page_img'] = theme('image', $params);
  };*/
  
  $variables['islandora_object_page_image'] = url("islandora/object/{$islandora_object->id}/datastream/"); // SEMANDRA - path to page images
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 * If an object's behavior is defined by the islandora_digitalus_islandora_digitalusCModel content model
 * this hook takes the object being displayed and sends it to the theme function described by islandora_digitalus_theme.
 * A reference to the islandora object being displayed is added here as a member of
 * the array whihc makes the seond argument to the theme function.
 */
function islandora_digitalus_islandora_digitalusCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_digitalus', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_islandora_ingest_steps().
 * This hook adds a single ingest step, but more could be added as seperate entries.
 */
function islandora_digitalus_islandora_digitalusCModel_islandora_ingest_steps(array $configuration) {
  return array(
    'islandora_digitalus_file_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_digitalus_upload_form',
      'module' => 'islandora_digitalus',
      'file' => 'includes/islandora_digitalus_upload.form.inc'
    )
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 * This hook tells Islandora what to do with the object once it has been ingested.
 * In this case the raw text has been uploaded so we'll be in a position to 
 * use that as input for our derived datastreams. The function
 * islandora_digitalus_create_all_derivatives will be called with a refrence to the 
 * as yet uningested object. 
 */
function islandora_digitalus_islandora_digitalusCModel_islandora_object_ingested($object) {
  module_load_include('inc', 'islandora_digitalus', 'includes/derivatives');
  islandora_digitalus_create_all_derivatives($object);
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 * This hook makes a predefined ingest form for ingest.
 */
function islandora_digitalus_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_digitalus');
  return array(
    'Digitalus MODS form' => array(
      'form_file' => "$module_path/xml/islandora_digitalus_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 * This hook associated our form with our content model.  Any time we try to ingest
 * an object with the islandora:digitalusCModel content model, we will see this form
 * allowing us to supply relevant metadata.
 */
function islandora_digitalus_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_digitalus_mods_form' => array(
      'content_model' => 'islandora:digitalusCModel',
      'form_name' => 'Digitalus MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 * This hook ingests a very basic content model.  It is run when the module is
 * first installed.
 */
function islandora_digitalus_islandora_required_objects(IslandoraTuque $connection) {
  $islandora_digitalus_content_model = $connection->repository->constructObject('islandora:digitalusCModel');
  $islandora_digitalus_content_model->owner = 'fedoraAdmin';
  $islandora_digitalus_content_model->label = 'Islandora Digital Page Model';
  $islandora_digitalus_content_model->models = 'fedora-system:ContentModel-3.0';

  return array(
    'islandora_digitalus' => array(
      'title' => 'Islandora Digital Page',
      'objects' => array(
        $islandora_digitalus_content_model,
      ),
    ),
  );
}